// Plugin discovery and bundling. Renderer halves (index.ts(x)) become IIFE
// expressions inlined into slick.js so they can be toggled without a reload;
// main halves (main.ts) are bundled into the loader, unreachable from the page.

import fs from 'node:fs';
import path from 'node:path';
import { build, type Plugin } from 'esbuild';
import { PLUGINS, ROOT, SHARED } from './paths.ts';

export type PluginEntry = { name: string; dir: string; renderer: string; main: string | null };

const RENDERER_NAMES = ['index.tsx', 'index.ts'];

export function discoverPlugins(): PluginEntry[] {
  if (!fs.existsSync(PLUGINS)) return [];

  return fs
    .readdirSync(PLUGINS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .map((entry) => {
      const dir = path.join(PLUGINS, entry.name);
      const renderer = RENDERER_NAMES.map((name) => path.join(dir, name)).find((file) => fs.existsSync(file));
      const mainFile = path.join(dir, 'main.ts');
      return { name: entry.name, dir, renderer: renderer ?? '', main: fs.existsSync(mainFile) ? mainFile : null };
    })
    .filter((entry) => {
      if (entry.renderer) return true;
      console.warn(`[build:plugins] ${entry.name} has no index.ts(x); skipping`);
      return false;
    })
    .toSorted((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
}

// `$slick` reads the host bundle's globals: a second compiled copy of
// SlickPlugin would fail `instanceof` and every plugin would be rejected.
const slickGlobalShim: Plugin = {
  name: 'slick-global-shim',
  setup(builder) {
    builder.onResolve({ filter: /^\$slick$/ }, () => ({ path: '$slick', namespace: 'slick-global' }));
    builder.onLoad({ filter: /.*/, namespace: 'slick-global' }, () => ({
      contents: `
        export const SlickPlugin = globalThis.__slick.SlickPlugin
        export default SlickPlugin
      `,
      loader: 'js',
    }));
  },
};

const slickSharedAlias: Plugin = {
  name: 'slick-shared-alias',
  setup(builder) {
    builder.onResolve({ filter: /^\$slick$/ }, () => ({ path: path.join(SHARED, 'Plugin.ts') }));
  },
};

export async function bundleRenderer(entry: PluginEntry, debug: boolean): Promise<string> {
  const result = await build({
    entryPoints: [entry.renderer],
    absWorkingDir: ROOT,
    bundle: true,
    write: false,
    platform: 'browser',
    format: 'esm',
    target: 'es2022',
    minify: !debug,
    sourcemap: false,
    jsx: 'transform',
    plugins: [slickGlobalShim],
    // Inline assets: fetching them would leak privacy and break offline.
    loader: { '.gif': 'dataurl', '.png': 'dataurl', '.svg': 'dataurl', '.woff2': 'dataurl' },
    define: { process: 'undefined' },
  });

  let code = `(() => {\n${result.outputFiles[0].text}\n})()`;
  code = code.replace(/export\s*\{\s*(\w+)\s+as\s+default\s*\};?/g, 'return $1;');
  code = code.replace(/export\s+default\s+(\w+);?/g, 'return $1;');

  if (!/\breturn\s+[A-Za-z_$][\w$]*\s*;/.test(code)) {
    throw new Error(`[build:plugins] ${entry.name} must default-export a named plugin class`);
  }
  return code;
}

export async function bundleAllRenderers(debug: boolean): Promise<Record<string, string>> {
  const plugins: Record<string, string> = {};
  for (const entry of discoverPlugins()) {
    plugins[entry.name] = await bundleRenderer(entry, debug);
  }
  console.log(`[build:plugins] ${Object.keys(plugins).length} renderer halves bundled`);
  return plugins;
}

// Written to a file, not resolved dynamically, so the set of privileged
// plugins is fixed at build time.
export function mainHalvesModule(): string {
  const all = discoverPlugins();
  const withMain = all.filter((entry) => entry.main);
  const withMeta = all.filter((entry) => fs.existsSync(path.join(entry.dir, 'meta.ts')));

  const lines = [
    '// Generated by scripts/lib/plugin.ts. Do not edit.',
    ...withMain.map((entry, index) => `import p${index} from ${JSON.stringify(entry.main)};`),
    ...withMeta.map((entry, index) => `import * as m${index} from ${JSON.stringify(path.join(entry.dir, 'meta.ts'))};`),
    '',
    `export const mainPlugins = [${withMain.map((_, index) => `p${index}`).join(', ')}];`,
    '',
    'export const pluginMeta = {',
    ...withMeta.map(
      (entry, index) =>
        `  ${JSON.stringify(entry.name)}: { schema: m${index}.settings, defaultEnabled: m${index}.defaultEnabled },`,
    ),
    '};',
    '',
  ];
  return lines.join('\n');
}

export { slickSharedAlias };
