// Plugin discovery and bundling. Renderer halves are statically imported into
// slick.js so they can be toggled without dynamic code evaluation;
// main halves (main.ts) are bundled into the loader, unreachable from the page.

import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'esbuild';
import { EXTENSION_PLUGINS } from '../../src/extension/plugins.ts';
import { PLUGINS, SHARED } from './paths.ts';

export type PluginEntry = { name: string; dir: string; renderer: string; main: string | null };

const RENDERER_NAMES = ['index.tsx', 'index.ts'];

export function discoverPlugins(): PluginEntry[] {
  if (!fs.existsSync(PLUGINS)) return [];

  return fs
    .readdirSync(PLUGINS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .map((entry) => {
      const dir = path.join(PLUGINS, entry.name);
      const renderer = RENDERER_NAMES.map((name) => path.join(dir, name)).find((file) => fs.existsSync(file));
      const mainFile = path.join(dir, 'main.ts');
      return { name: entry.name, dir, renderer: renderer ?? '', main: fs.existsSync(mainFile) ? mainFile : null };
    })
    .filter((entry) => {
      if (entry.renderer) return true;
      console.warn(`[build:plugins] ${entry.name} has no index.ts(x); skipping`);
      return false;
    })
    .toSorted((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
}

const slickSharedAlias: Plugin = {
  name: 'slick-shared-alias',
  setup(builder) {
    builder.onResolve({ filter: /^\$slick$/ }, () => ({ path: path.join(SHARED, 'Plugin.ts') }));
  },
};

export type RendererRegistryOptions = {
  targetLoader?: 'electron' | 'extension';
  /** Explicit selection overrides the target default. Unknown names fail the build. */
  pluginNames?: readonly string[];
};

export { EXTENSION_PLUGINS as EXTENSION_PLUGIN_NAMES };

export function rendererRegistryModule({
  targetLoader = 'electron',
  pluginNames,
}: RendererRegistryOptions = {}): string {
  const all = discoverPlugins();
  const names = pluginNames ?? (targetLoader === 'extension' ? EXTENSION_PLUGINS : undefined);
  if (names) {
    const available = new Set(all.map((entry) => entry.name));
    for (const name of names) {
      if (!available.has(name)) throw new Error(`[build:plugins] unknown renderer plugin: ${name}`);
    }
  }
  const selected = names ? all.filter((entry) => names.includes(entry.name)) : all;
  return [
    ...selected.map((entry, index) => `import p${index} from ${JSON.stringify(entry.renderer)};`),
    'export default {',
    ...selected.map((entry, index) => `  [${JSON.stringify(entry.name)}]: p${index},`),
    '};',
  ].join('\n');
}

/** Bundle constructors in the host graph, sharing its SlickPlugin class identity. */
export function rendererRegistryPlugin(options: RendererRegistryOptions = {}): Plugin {
  return {
    name: 'slick-plugins',
    setup(builder) {
      builder.onResolve({ filter: /^slick:plugins$/ }, () => ({ path: 'slick:plugins', namespace: 'slick-plugins' }));
      builder.onLoad({ filter: /.*/, namespace: 'slick-plugins' }, () => ({
        contents: rendererRegistryModule(options),
        resolveDir: PLUGINS,
        loader: 'js',
      }));
    },
  };
}

// Written to a file, not resolved dynamically, so the set of privileged
// plugins is fixed at build time.
export function mainHalvesModule(): string {
  const all = discoverPlugins();
  const withMain = all.filter((entry) => entry.main);
  const withMeta = all.filter((entry) => fs.existsSync(path.join(entry.dir, 'meta.ts')));

  const lines = [
    '// Generated by scripts/lib/plugin.ts. Do not edit.',
    ...withMain.map((entry, index) => `import p${index} from ${JSON.stringify(entry.main)};`),
    ...withMeta.map((entry, index) => `import * as m${index} from ${JSON.stringify(path.join(entry.dir, 'meta.ts'))};`),
    '',
    `export const mainPlugins = [${withMain.map((_, index) => `p${index}`).join(', ')}];`,
    '',
    'export const pluginMeta = {',
    ...withMeta.map(
      (entry, index) =>
        `  ${JSON.stringify(entry.name)}: { schema: m${index}.settings, defaultEnabled: m${index}.defaultEnabled },`,
    ),
    '};',
    '',
  ];
  return lines.join('\n');
}

export { slickSharedAlias };
